server:
  port: 9091

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka


spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: USER-SERVICE
                fallbackuri: forward:/userServiceFallBack
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-SERVICE
                fallbackuri: forward:/departmentServiceFallBack

        - id: RESTAURANT-SERVICE
          uri:
            lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurant/**

        - id: FOOD-CATALOGUE-SERVICE
          uri:
            lb://FOOD-CATALOGUE-SERVICE
          predicates:
            - Path=/fooditems/**
        - id: ORDER-SERVICE
          uri:
            lb://ORDER-SERVICE
          predicates:
            - Path=/order/**


hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream



